### PR TITLE
[ENH] Command line accepts explicit participant and group invocation

### LINKED ISSUE #307: make it possible to specify to do all levels (all avail participant + group)
tried e.g. this way to fail ;)
```shell
$> docker run --rm -it -v "${PWD}:/data:ro" -v "${PWD}/derivatives/mriqc:/outputs:rw" poldracklab/mriqc:latest /data /outputs participant,group
/usr/local/miniconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
usage: mriqc [-h] [-v]
             [--participant_label [PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]]
             [-d [{anat,anatomical,func,functional} [{anat,anatomical,func,functional} ...]]]
             [-s SESSION_ID] [-r RUN_ID] [--nthreads NTHREADS]
             [--n_procs N_PROCS] [--mem_gb MEM_GB] [--write-graph] [--dry-run]
             [--use-plugin USE_PLUGIN] [--testing] [-w WORK_DIR]
             [--report-dir REPORT_DIR] [--verbose-reports]
             [--ants-nthreads ANTS_NTHREADS] [--ants-settings ANTS_SETTINGS]
             [--hmc-afni] [--deoblique] [--despike] [--start-idx START_IDX]
             [--stop-idx STOP_IDX] [--correct-slice-timing]
             bids_dir output_dir {participant,group}
mriqc: error: argument analysis_level: invalid choice: 'participant,group' (choose from u'participant', u'group')
```

ideally, e.g. for "auto-group" mode instead of complaining like 
```shell




unctions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
161123-02:54:11,764 mriqc INFO:
	 Running MRIQC-0.8.8-2 (analysis_level=group, participant_label=None)
	Settings={u'report_dir': u'/outputs/reports', u'work_dir': u'/scratch/work', u'n_procs': 2, u'bids_dir': '/data', u'hmc_afni': False, u'write_graph': False, u'ants_nthreads': 6, u'verbose_reports': False, u'testing': False, u'output_dir': '/outputs'}
161123-02:54:11,937 mriqc WARNING:
	 No IQM-JSON files were found for the anatomical data type in /outputs/derivatives. The group-level report was not generated.
161123-02:54:11,938 mriqc WARNING:
	 No IQM-JSON files were found for the functional data type in /outputs/derivatives. The group-level report was not generated.
```
it could just run participant level analysis and then aggregate all those found and computed into the group level.  Additional switch "--recompute" (or alike) could trigger recomputation at participant level as well

### PR DESCRIPTION
**Pull request by oesteban**
Now, it will be possible to run:

```
mriqc data/ out/ participant group
```
or
```
mriqc data/ out/ participant group --participant_label S002 S003
```

The original commandline for participant level without --participant_label
will run both levels, as before.

Closes #307

### CODE REVIEW

**Comment by chrisfilo** [comment]
I wonder if it wouldn't make sense to simplify this even further

mriqc data/ out

**Comment by oesteban** [comment]
Sure, that would be BIDS-Apps compatible?

**Comment by chrisfilo** [comment]
not really, but neither is

mriqc data/ out/ participant group

**Comment by oesteban** [comment]
Let's add this that has been specifically asked for, and think about the possibility of not giving participant arg at all as suggested.

**Comment by yarikoptic** [comment]
thanks!

**Pull request merged**
