### PR TITLE
[FIX] Implement filters for session, run and task of BIDS input

### PR DESCRIPTION
**Pull request by jvarada**
Fix for #601 

@oesteban Can this get expedited code review? Really waiting on this to move forward with our analysis. Thanks!

### CODE REVIEW

**Comment by oesteban** [comment]
@jvarada it seems that querying anatomical scans is still failing... let me know if you need any help

**Comment by jvarada** [comment]
@oesteban Just figured out the problem, will update code later tonight.

**Comment by jvarada** [comment]
@oesteban Tests passing now.

**Comment by oesteban** [comment]
Thanks a lot @jvarada. Awesome contribution.

**Pull request merged**
