### PR TITLE
[ENH] Use versioneer to handle versions

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by chrisfilo** [comment]
Is there a reason why versioneer code is copied instead of installed via pip?

**Comment by oesteban** [comment]
Tried to remove the file and it doesn't work. Maybe versioneer is not a requirement. I'll check that.

**Comment by oesteban** [comment]
Ok, so versioneer is needed as a dependency, and also the versioneer.py file is required during setup. Last commit should fix a problem when requesting mriqc version in an environment where a full installation was done (`pip install mriqc`).

**Comment by oesteban** [comment]
BTW, this is pretty cool because it also tells you if your current version is _dirty_ (meaning there are changes not committed yet).

**Comment by oesteban** [comment]
Seems to be working

**Pull request merged**
