### PR TITLE
[RTM] add reproducibility of metrics tracking

### LINKED ISSUE #452: Test metrics value stability on CircleCI
Test should fail if the values from our test data diverge too much from prescribed range (defined empirically). This could use the same data as #451

### PR DESCRIPTION
**Pull request by oesteban**
This a first stab at checking reliability of measures. Closes #452.

### CODE REVIEW

**Comment by chrisfilo** [comment]
Testing if it truly breaks if measures change.

It also would be useful to provide information on which modality and which measure changed specifically instead of saying that something changed.

**Comment by oesteban** [comment]
Yes - for future improvements we can follow this http://stackoverflow.com/questions/17095101/outputting-difference-in-two-pandas-dataframes-side-by-side-highlighting-the-d

**Comment by chrisfilo** [comment]
Seems like an easy addition - I would recommend doing it. It will save us
time in the future.

**Comment by oesteban** [comment]
Ok 👍

**Pull request merged**
