### PR TITLE
[RTM] PIN: Update niworkflows

### PR DESCRIPTION
**Pull request by effigies**
Includes: nipy/nipype#2198, nipy/nipype#2200

Depends: poldracklab/niworkflows#197

### CODE REVIEW

**Comment by effigies** [comment]
Still needs to be pinned against effigies until we merge poldracklab/niworkflows#197.

**Comment by oesteban** [comment]
Bummer! fixing right now. Thanks for the heads up

**Comment by oesteban** [comment]
You can cancel https://circleci.com/gh/effigies/mriqc/15 if you want, now the tip is https://circleci.com/gh/effigies/mriqc/16

**Comment by effigies** [comment]
Latest failure is a minor issue unrelated to niworkflows/nipype, so going to merge niworkflows pin unless fmriprep fails. Fixed in latest commit. Will push a new pin once merged, and MRIQC can go through a full test then.

**Comment by effigies** [comment]
@oesteban I think this is good to go.

**Pull request merged**
