### PR TITLE
Change size datatype from uint8 to uint16 for sizes > 256

### PR DESCRIPTION
**Pull request by wtriplett**
addresses #40

### CODE REVIEW

**Comment by oesteban** [comment]
fixes #40 , right?

**Comment by oesteban** [comment]
I owe you some explanations: if you include 'fixes #40' or variation (fix, close, closes) in your commit message, github will automatically close the issue for you when merged :)

**Comment by wtriplett** [comment]
Thanks Oscar. I guess "addresses" isn't strong enough language for GitHub. :)

**Comment by oesteban** [comment]
Yeah, that's how it looks.

**Pull request merged**
