### PR TITLE
MAINT: Use PyBIDS 0.9.2+ via niworkflows PR

### LINKED ISSUE #776: Bump up to pybids 0.9
I would recommend skipping 0.7 altogether. This is related to [neurostars #3713](https://neurostars.org/t/no-module-named-bids-grabbids/3713), which is a custom installation running across a failure to import `bids.grabbids`. It's not clear how deep a rabbit hole moving up to 0.8 will end up being, so I'm starting an issue. If you don't have time, I can give it a shot this afternoon.

### PR DESCRIPTION
**Pull request by effigies**
Closes #776.

### CODE REVIEW

**Comment by effigies** [comment]
Travis failure is just whining about the URL in setup. Will be resolved once niworkflows has a release.

**Comment by effigies** [comment]
@oesteban I suspect this is something you'll know more about:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/bin/mriqc_run.py", line 418, in init_mriqc
    wf_list.append(build_workflow(dataset[mod], mod, settings=settings))
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/core.py", line 25, in build_workflow
    workflow = fmri_qc_workflow(dataset, settings=settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/functional.py", line 111, in fmri_qc_workflow
    ema = epi_mni_align(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/workflows/functional.py", line 718, in epi_mni_align
    template_resolution=2, ),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 32, in __init__
    super(ReportCapableInterface, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 100, in __init__
    super(RobustMNINormalization, self).__init__(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 175, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/specs.py", line 67, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'moving' trait of a RobustMNINormalizationInputSpecRPT instance must be 'T1w' or 'boldref', but a value of 'bold' <class 'str'> was specified.
```

We can naively replace `bold` with `boldref` here:

https://github.com/poldracklab/mriqc/blob/f38b344655e37b25e7e8f6af373f8c361874a7b8/mriqc/workflows/functional.py#L710

But I'm not sure if that's actually appropriate.

**Comment by oesteban** [comment]
It is actually necessary - https://github.com/poldracklab/niworkflows/pull/368

I forgot to check on MRIQC when merged that PR.

**Comment by effigies** [comment]
> It is actually necessary - [poldracklab/niworkflows#368](https://github.com/poldracklab/niworkflows/pull/368)
> 
> I forgot to check on MRIQC when merged that PR.

To be clear, I *should* change that to `boldref`, or we need to restore `bold` to the interface options?

**Comment by oesteban** [comment]
It is boldref now, you have to change it. Sorry for the confusion

**Pull request merged**
