### PR TITLE
[ENH] Add --fd_thres command line option

### PR DESCRIPTION
**Pull request by jdkent**
I added the option to manually set fd_thres to another value besides 0.2, but kept the default to be 0.2. The checks to set fd_thres to 0.2 may have some redundancy and be unnecessary, but I've kept them in for now. Being able to change this option is useful to me since I work with data that often breaks the 0.2 threshold, and setting a higher threshold gives me a clearer sense of how "usable" the data is. Feedback is always welcomed on how I can improve my contribution.

Thanks!
James

### CODE REVIEW

**Comment by chrisfilo** [comment]
This looks reasonable to me. @jdkent are you planning to add anything to this PR? @oesteban maybe this could go into the upcoming release?

**Comment by oesteban** [comment]
Yes, we can definitely add it if all tests pass.

**Comment by jdkent** [comment]
@chrisfilo I'm not planning on adding anything else to the PR, especially if you are trying to get a release out. I will eventually try to implement #206 since this is the first small step to accomplish that goal.

**Comment by oesteban** [comment]
Sorry, I messed up trying to merge with upstream/master (so that only the pertinent changes are shown). Obviously that did not produced my expected results.

**Pull request merged**
