### PR TITLE
[Docker] Refactor docker images and building in Circle

### LINKED ISSUE #421: [PY2] Unicode error when generating reports
```
Traceback (most recent call last):
  File "/work/01329/poldrack/software/anaconda2-4.2.0/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.0.post0', 'console_scripts', 'mriqc')()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/mriqc-0.9.0.post0-py2.7.egg/mriqc/bin/mriqc_run.py", line 289, in main
    out_file=out_html)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/mriqc-0.9.0.post0-py2.7.egg/mriqc/reports/group.py", line 166, in gen_html
    }, out_file)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/mriqc-0.9.0.post0-py2.7.egg/mriqc/data/config.py", line 33, in generate_conf
    output = self.compile(configs)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/mriqc-0.9.0.post0-py2.7.egg/mriqc/data/config.py", line 29, in compile
    return template.render(configs)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/mriqc-0.9.0.post0-py2.7.egg/mriqc/data/reports/group.html", line 25, in top-level template code
    <li>MRIQC version: {{ version }}.</li>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 7314: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by oesteban**
This PR refactors the Docker image to make it easier to build both Python 3.5 and 2.7 versions for testing.

It should also address #395.

### CODE REVIEW

**Comment by chrisfilo** [comment]
Have a look at the work by @effigies on fmriprep to speed up building docker containers on CircleCI:
https://github.com/poldracklab/fmriprep/pull/465
https://github.com/poldracklab/fmriprep/pull/472

**Comment by oesteban** [comment]
Interesting! The rationale behind adding an intermediate base image is to be able to do something like that pull in poldracklab/fmriprep#465

Regarding poldracklab/fmriprep#472, yes, we will probably end up giving up on Circle caching for mriqc as well :(

**Comment by chrisfilo** [comment]
I think what the improvement in poldracklab/fmriprep#465 has shown is that you do not need to make an explicit separate base Docker image. You just pull the previously released version from Docker hub and when building the heavy first few layers get reused and only the light final layers get actually rebuild.

**Comment by effigies** [comment]
As a comment, I think it makes sense to schedule any changes to the heavy base layers for just before some release, so you're not both pulling and then building mostly from scratch every time.

**Pull request closed without merging**
