### PR TITLE
[ENH] Copy BIDS interfaces from fmriprep

### PR DESCRIPTION
**Pull request by oesteban**
A first take on #23

### CODE REVIEW

**Comment by oesteban** [comment]
Add some metadata in the test dataset to check this is really functional

**Comment by chrisfilo** [comment]
If the Interfaces are shared between fmriprep and mriqc maybe it's worth
putting them in nipype?

**Comment by oesteban** [comment]
Definitely. I am currently testing it (there's only one for retrieving the metadata associated to the in_file), and it apparently works fine.

Another option is to include the interface within pybids.

**Comment by chrisfilo** [comment]
I think nipype is a better place for them. It would be nice if we could
avoid nipype dependency in pybids.

**Pull request merged**
