### PR TITLE
[ENH] Clip outliers in FD and SPIKES group plots

### LINKED ISSUE #313: FD count distribution unreadable
image

### LINKED ISSUE #445: Make metric labels from reports link to their respective descriptions in online docuementation

### PR DESCRIPTION
**Pull request by oesteban**
This will allow to see the distribution while removing outliers
that force the range shown in the scatterplot.

Fixes #313

### CODE REVIEW

**Comment by chrisfilo** [comment]
How does it look?

I would be careful clipping outliers since outliers are probably what everyone is looking for in those graphs.

**Comment by oesteban** [comment]
https://1333-54756129-gh.circle-artifacts.com/1/home/ubuntu/scratch/out/reports/bold_group.html

It only clips the FD and the SPIKES (num). If we see it works well, we can include the DUMMY (trs).

**Comment by chrisfilo** [comment]
I have to say I find this misleading. You really have to know that clipping might happen and check all of the extreme data points to see how much of an outlier it really was.

**Comment by oesteban** [comment]
It is. The only real solution to these problems would be implementing
zooming in/out

**Comment by chrisfilo** [comment]
Out of the two non-real solutions I would say lack of clipping (and
compression of the main body of the distribution) is a better solution than
misrepresentation due to clipping.

**Pull request merged**
